//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.13 at 02:01:33 PM CDT 
//


package edu.bcm.dldcc.big.nursa.util.restapi.client.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the foo.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: foo.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PubmedArticleSet }
     * 
     */
    public PubmedArticleSet createPubmedArticleSet() {
        return new PubmedArticleSet();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle }
     * 
     */
    public PubmedArticleSet.PubmedArticle createPubmedArticleSetPubmedArticle() {
        return new PubmedArticleSet.PubmedArticle();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.PubmedData }
     * 
     */
    public PubmedArticleSet.PubmedArticle.PubmedData createPubmedArticleSetPubmedArticlePubmedData() {
        return new PubmedArticleSet.PubmedArticle.PubmedData();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.PubmedData.ArticleIdList }
     * 
     */
    public PubmedArticleSet.PubmedArticle.PubmedData.ArticleIdList createPubmedArticleSetPubmedArticlePubmedDataArticleIdList() {
        return new PubmedArticleSet.PubmedArticle.PubmedData.ArticleIdList();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.PubmedData.History }
     * 
     */
    public PubmedArticleSet.PubmedArticle.PubmedData.History createPubmedArticleSetPubmedArticlePubmedDataHistory() {
        return new PubmedArticleSet.PubmedArticle.PubmedData.History();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation createPubmedArticleSetPubmedArticleMedlineCitation() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList createPubmedArticleSetPubmedArticleMedlineCitationMeshHeadingList() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading createPubmedArticleSetPubmedArticleMedlineCitationMeshHeadingListMeshHeading() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.ChemicalList }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.ChemicalList createPubmedArticleSetPubmedArticleMedlineCitationChemicalList() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.ChemicalList();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article createPubmedArticleSetPubmedArticleMedlineCitationArticle() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.AuthorList }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.AuthorList createPubmedArticleSetPubmedArticleMedlineCitationArticleAuthorList() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.AuthorList();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal createPubmedArticleSetPubmedArticleMedlineCitationArticleJournal() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.JournalIssue }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.JournalIssue createPubmedArticleSetPubmedArticleMedlineCitationArticleJournalJournalIssue() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.JournalIssue();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.PubmedData.ArticleIdList.ArticleId }
     * 
     */
    public PubmedArticleSet.PubmedArticle.PubmedData.ArticleIdList.ArticleId createPubmedArticleSetPubmedArticlePubmedDataArticleIdListArticleId() {
        return new PubmedArticleSet.PubmedArticle.PubmedData.ArticleIdList.ArticleId();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.PubmedData.History.PubMedPubDate }
     * 
     */
    public PubmedArticleSet.PubmedArticle.PubmedData.History.PubMedPubDate createPubmedArticleSetPubmedArticlePubmedDataHistoryPubMedPubDate() {
        return new PubmedArticleSet.PubmedArticle.PubmedData.History.PubMedPubDate();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.PMID }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.PMID createPubmedArticleSetPubmedArticleMedlineCitationPMID() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.PMID();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.DateCreated }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.DateCreated createPubmedArticleSetPubmedArticleMedlineCitationDateCreated() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.DateCreated();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.DateCompleted }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.DateCompleted createPubmedArticleSetPubmedArticleMedlineCitationDateCompleted() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.DateCompleted();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.DateRevised }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.DateRevised createPubmedArticleSetPubmedArticleMedlineCitationDateRevised() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.DateRevised();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.MedlineJournalInfo }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.MedlineJournalInfo createPubmedArticleSetPubmedArticleMedlineCitationMedlineJournalInfo() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.MedlineJournalInfo();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading.DescriptorName }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading.DescriptorName createPubmedArticleSetPubmedArticleMedlineCitationMeshHeadingListMeshHeadingDescriptorName() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading.DescriptorName();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading.QualifierName }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading.QualifierName createPubmedArticleSetPubmedArticleMedlineCitationMeshHeadingListMeshHeadingQualifierName() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.MeshHeadingList.MeshHeading.QualifierName();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.ChemicalList.Chemical }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.ChemicalList.Chemical createPubmedArticleSetPubmedArticleMedlineCitationChemicalListChemical() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.ChemicalList.Chemical();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Pagination }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Pagination createPubmedArticleSetPubmedArticleMedlineCitationArticlePagination() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Pagination();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.PublicationTypeList }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.PublicationTypeList createPubmedArticleSetPubmedArticleMedlineCitationArticlePublicationTypeList() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.PublicationTypeList();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.AuthorList.Author }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.AuthorList.Author createPubmedArticleSetPubmedArticleMedlineCitationArticleAuthorListAuthor() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.AuthorList.Author();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.ISSN }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.ISSN createPubmedArticleSetPubmedArticleMedlineCitationArticleJournalISSN() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.ISSN();
    }

    /**
     * Create an instance of {@link PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.JournalIssue.PubDate }
     * 
     */
    public PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.JournalIssue.PubDate createPubmedArticleSetPubmedArticleMedlineCitationArticleJournalJournalIssuePubDate() {
        return new PubmedArticleSet.PubmedArticle.MedlineCitation.Article.Journal.JournalIssue.PubDate();
    }

}
